name: Build and Push Processor

on:
  push:
    branches:
      - development2
      - production
      - update_tf
env:
  CARGO_TERM_COLOR: always

jobs:
  # deploy on pushes to master branch
  # assumes aws credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) are set in github secrets
  push_dev:
    if: github.ref == 'refs/heads/update_tf'
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
      # - name: Install Musl-gcc
      #   run: |
      #     sudo apt update -y
      #     sudo apt install -y musl-tools
          
      # - name: Set up Rust
      #   uses: hecrj/setup-rust-action@v1
      #   with:
      #     targets: x86_64-unknown-linux-musl

      # - name: Checkout
      #   uses: actions/checkout@v2
        
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-1
          
      # - name: Build and Push for Dev
      #   working-directory: example-dynamodb-lambda
      #   run: |
      #     cargo build --release --target x86_64-unknown-linux-musl          
      #     cp ./target/x86_64-unknown-linux-musl/release/my-table ./bootstrap && zip my-table.zip bootstrap && rm bootstrap
      #     aws s3 cp ./my-table.zip s3://891616054205-ap-southeast-1-aws-lambda/dev-sg-hocvienconggiao/${{ github.event.repository.name }}/latest/dynamodb/my-table.zip

      - name: Build and Push PdfGenerator for Dev
        working-directory: pdf-generator-lambda
        run: |
          yarn build --production
          mv ./node_modules ./dist/ && zip pdf-generator.zip ./dist/* && rm pdf-generator.zip
          aws s3 cp ./pdf-generator.zip s3://891616054205-ap-southeast-1-aws-lambda/dev-sg-hocvienconggiao/${{ github.event.repository.name }}/latest/dynamodb/pdf-generator.zip

      - name: Deploy Terraform Config 
        run: |
          chmod +x ./scripts/terraform-enterprise-push.sh
          ./scripts/terraform-enterprise-push.sh pdf-generator-lambda/terraform HocVienCongGiao/dev-sg-lambda-processors-dynamodb-student-application-pdf